on:
  pull_request:
# add "synchronize" in "types", in order to trigger workflow for pull request commit(s) pushes.
    types: [open, synchronize]
    branches: [develop]
name: Run debug unit tests
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: ./middleware.sh ${{ secrets.ANYTYPE_SECRET }}
      - run: ./gradlew assembleDebug test -Dpre-dex=false
