on:
  push:
    branches: feature/599-turn-on-read-mode
name: CI
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: ./middleware.sh ${{ secrets.ANYTYPE_SECRET }}
      - run: ./gradlew build test -Dpre-dex=false
      - uses: actions/upload-artifact@master
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
